-- 코드를 입력하세요
SELECT I.FLAVOR
FROM ICECREAM_INFO AS I
JOIN FIRST_HALF AS H
ON I.FLAVOR = H.FLAVOR
WHERE H.TOTAL_ORDER > 3000 AND I.INGREDIENT_TYPE = 'fruit_based'
GROUP BY I.FLAVOR
ORDER BY H.TOTAL_ORDER DESC;